# 02_cleaning.ipynb

This notebook follows the in-class data cleaning pipeline:

1. Inspect  
2. Diagnose  
3. Missing values  
4. Duplicates  
5. Type conversion  
6. Validate and export

**Input:** `问卷数据.csv`  
**Output:** `questionnaire_cleaned.csv`

In [1]:

import pandas as pd
import numpy as np

raw_path = r"/mnt/data/问卷数据.csv"
df_raw = pd.read_csv(raw_path, encoding="gb2312")
print("Loaded raw data:", df_raw.shape)
df_raw.head()

Loaded raw data: (213, 19)

    随机元素 您是否同意参加本次研究？ 您线上购买服饰的频率？  ... Unnamed: 16 Unnamed: 17 Unnamed: 18
0   随机元素           Q1          Q2  ...         NaN         NaN         NaN
1  实验情境4   我同意并愿意继续作答          经常  ...         NaN         NaN         NaN
2  实验情境4   我同意并愿意继续作答          经常  ...         NaN         NaN         NaN
3  实验情境4   我同意并愿意继续作答          有时  ...         NaN         NaN         NaN
4  实验情境1   我同意并愿意继续作答          有时  ...         NaN         NaN         NaN

[5 rows x 19 columns]

## 1. Inspect

In [2]:
print("Shape:", df_raw.shape)
display(df_raw.head())
print("\nInfo:")
df_raw.info()
print("\nDtypes:")
display(df_raw.dtypes)

Shape: (213, 19)

    随机元素 您是否同意参加本次研究？ 您线上购买服饰的频率？  ... Unnamed: 16 Unnamed: 17 Unnamed: 18
0   随机元素           Q1          Q2  ...         NaN         NaN         NaN
1  实验情境4   我同意并愿意继续作答          经常  ...         NaN         NaN         NaN
2  实验情境4   我同意并愿意继续作答          经常  ...         NaN         NaN         NaN
3  实验情境4   我同意并愿意继续作答          有时  ...         NaN         NaN         NaN
4  实验情境1   我同意并愿意继续作答          有时  ...         NaN         NaN         NaN

[5 rows x 19 columns]

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213 entries, 0 to 212
Data columns (total 19 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   随机元素                                   213 non-null    object
 1   您是否同意参加本次研究？                           213 non-null    object
 2   您线上购买服饰的频率？                            213 non-null    object
 3   您是否购买过与 AI 相关的产品或服务？                   213 non-null    object
 4   您的年龄                                   213 non-null    object
 5   如果由您决定，您最多愿意为这件 T-shirt 支付多少钱？（0-500）  213 non-null    object
 6   我愿意为这件 T-shirt 支付较高的价格。                213 non-null    object
 7   我认为这件 T-shirt 值得这个价格。                  213 non-null    object
 8   我认为这种设计来源是可靠的。                         213 non-null    object
 9   我相信这种设计来源能够完成高质量的产品设计。                 213 non-null    object
 10  总体而言，我信任这种设计来源                         213 non-null    object
 11  我对人工智能（AI）有基本了解                        213 non-null    object
 12  我平时经常接触 AI 工具或应用                       213 non-null    object
 13  我比较熟悉 AI 在产品设计中的应用                     213 non-null    object
 14  我认为这件 T-shirt 是由 AI 完成设计的。             213 non-null    object
 15  我认为这件 T-shirt 属于附加价值较高的产品。             213 non-null    object
 16  Unnamed: 16                            0 non-null      float64
 17  Unnamed: 17                            0 non-null      float64
 18  Unnamed: 18                            0 non-null      float64
dtypes: float64(3), object(16)
memory usage: 31.7+ KB

Dtypes:

随机元素                                      object
您是否同意参加本次研究？                              object
您线上购买服饰的频率？                               object
您是否购买过与 AI 相关的产品或服务？                      object
您的年龄                                      object
如果由您决定，您最多愿意为这件 T-shirt 支付多少钱？（0-500）     object
我愿意为这件 T-shirt 支付较高的价格。                   object
我认为这件 T-shirt 值得这个价格。                     object
我认为这种设计来源是可靠的。                            object
我相信这种设计来源能够完成高质量的产品设计。                    object
总体而言，我信任这种设计来源                            object
我对人工智能（AI）有基本了解                           object
我平时经常接触 AI 工具或应用                          object
我比较熟悉 AI 在产品设计中的应用                        object
我认为这件 T-shirt 是由 AI 完成设计的。                object
我认为这件 T-shirt 属于附加价值较高的产品。                object
Unnamed: 16                              float64
Unnamed: 17                              float64
Unnamed: 18                              float64
dtype: object

## 2. Diagnose

In [3]:
print("Missing values by column:")
display(df_raw.isnull().sum().to_frame("missing_count"))

print("\nDuplicate rows:", df_raw.duplicated().sum())

for col in df_raw.columns:
    print(f"\nColumn: {col}")
    print(df_raw[col].dropna().astype(str).head(5).tolist())

Missing values by column:

                                       missing_count
随机元素                                               0
您是否同意参加本次研究？                                       0
您线上购买服饰的频率？                                        0
您是否购买过与 AI 相关的产品或服务？                               0
您的年龄                                               0
如果由您决定，您最多愿意为这件 T-shirt 支付多少钱？（0-500）              0
我愿意为这件 T-shirt 支付较高的价格。                            0
我认为这件 T-shirt 值得这个价格。                              0
我认为这种设计来源是可靠的。                                     0
我相信这种设计来源能够完成高质量的产品设计。                             0
总体而言，我信任这种设计来源                                     0
我对人工智能（AI）有基本了解                                    0
我平时经常接触 AI 工具或应用                                   0
我比较熟悉 AI 在产品设计中的应用                                 0
我认为这件 T-shirt 是由 AI 完成设计的。                         0
我认为这件 T-shirt 属于附加价值较高的产品。                         0
Unnamed: 16                                      213
Unnamed: 17                                      213
Unnamed: 18                                      213

Duplicate rows: 0

Column: 随机元素
['随机元素', '实验情境4', '实验情境4', '实验情境4', '实验情境1']

Column: 您是否同意参加本次研究？
['Q1', '我同意并愿意继续作答', '我同意并愿意继续作答', '我同意并愿意继续作答', '我同意并愿意继续作答']

Column: 您线上购买服饰的频率？
['Q2', '经常', '经常', '有时', '有时']

Column: 您是否购买过与 AI 相关的产品或服务？
['Q3', '否', '是', '否', '是']

Column: 您的年龄
['Q4', '28-32', '18-22', '33及以上', '18-22']

Column: 如果由您决定，您最多愿意为这件 T-shirt 支付多少钱？（0-500）
['Q5', '121', '138', '117', '177']

Column: 我愿意为这件 T-shirt 支付较高的价格。
['Q6', '5', '6', '3', '5']

Column: 我认为这件 T-shirt 值得这个价格。
['Q7', '6', '5', '4', '6']

Column: 我认为这种设计来源是可靠的。
['Q8', '6', '7', '5', '6']

Column: 我相信这种设计来源能够完成高质量的产品设计。
['Q9', '4', '4', '5', '6']

Column: 总体而言，我信任这种设计来源
['Q10', '6', '4', '5', '5']

Column: 我对人工智能（AI）有基本了解
['Q11', '5', '4', '4', '7']

Column: 我平时经常接触 AI 工具或应用
['Q12', '4', '6', '1', '4']

Column: 我比较熟悉 AI 在产品设计中的应用
['Q13', '2', '4', '4', '5']

Column: 我认为这件 T-shirt 是由 AI 完成设计的。
['Q14', '1', '2', '2', '6']

Column: 我认为这件 T-shirt 属于附加价值较高的产品。
['Q15', '2', '1', '3', '6']

Column: Unnamed: 16
[]

Column: Unnamed: 17
[]

Column: Unnamed: 18
[]

### Diagnosis notes
- The file contains three empty columns named `Unnamed:*`.
- The first row is not a real response. It repeats question identifiers and should be removed.
- Numeric survey answers are stored as text and need conversion.
- The experimental group column can be used to derive `design_source` and `added_value`.

## 3–5. Clean: missing values, duplicates, type conversion

In [4]:
df = df_raw.copy()

# Drop empty columns
df = df.loc[:, ~df.columns.str.contains(r"^Unnamed")]

# Remove the non-response header/code row
df = df[df["随机元素"] != "随机元素"].copy()

# Rename columns to analysis-friendly names
rename_map = {
    "随机元素": "group",
    "您是否同意参加本次研究？": "consent",
    "您线上购买服饰的频率？": "shopping_freq",
    "您是否购买过与 AI 相关的产品或服务？": "ai_purchase",
    "您的年龄": "age_group",
    "如果由您决定，您最多愿意为这件 T-shirt 支付多少钱？（0-500）": "wtp_open",
    "我愿意为这件 T-shirt 支付较高的价格。": "wtp_1",
    "我认为这件 T-shirt 值得这个价格。": "wtp_2",
    "我认为这种设计来源是可靠的。": "trust_1",
    "我相信这种设计来源能够完成高质量的产品设计。": "trust_2",
    "总体而言，我信任这种设计来源": "trust_3",
    "我对人工智能（AI）有基本了解": "fam_1",
    "我平时经常接触 AI 工具或应用": "fam_2",
    "我比较熟悉 AI 在产品设计中的应用": "fam_3",
    "我认为这件 T-shirt 是由 AI 完成设计的。": "mc_ai",
    "我认为这件 T-shirt 属于附加价值较高的产品。": "mc_value",
}
df = df.rename(columns=rename_map)

# Convert numeric columns
numeric_cols = [
    "wtp_open", "wtp_1", "wtp_2",
    "trust_1", "trust_2", "trust_3",
    "fam_1", "fam_2", "fam_3",
    "mc_ai", "mc_value"
]
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Create experimental condition variables
df["design_source"] = df["group"].map({
    "实验情境1": 1,
    "实验情境2": 1,
    "实验情境3": 0,
    "实验情境4": 0
})
df["added_value"] = df["group"].map({
    "实验情境1": 1,
    "实验情境2": 0,
    "实验情境3": 1,
    "实验情境4": 0
})

# Convert some columns to ordered categories
df["age_group"] = pd.Categorical(
    df["age_group"],
    categories=["18-22", "23-27", "28-32", "33及以上"],
    ordered=True
)
df["shopping_freq"] = pd.Categorical(
    df["shopping_freq"],
    categories=["很少", "偶尔", "有时", "经常", "非常频繁"],
    ordered=True
)
df["ai_purchase"] = pd.Categorical(
    df["ai_purchase"],
    categories=["否", "不确定", "是"],
    ordered=True
)

# Construct scale scores
df["wtp_score"] = df[["wtp_1", "wtp_2"]].mean(axis=1)
df["trust_score"] = df[["trust_1", "trust_2", "trust_3"]].mean(axis=1)
df["ai_familiarity"] = df[["fam_1", "fam_2", "fam_3"]].mean(axis=1)

# Reset index after cleaning
df = df.reset_index(drop=True)

print("Cleaned shape:", df.shape)
display(df.head())

Cleaned shape: (212, 21)

   group     consent shopping_freq  ... wtp_score trust_score  ai_familiarity
0  实验情境4  我同意并愿意继续作答            经常  ...       5.5    5.333333        3.666667
1  实验情境4  我同意并愿意继续作答            经常  ...       5.5    5.000000        4.666667
2  实验情境4  我同意并愿意继续作答            有时  ...       3.5    5.000000        3.000000
3  实验情境1  我同意并愿意继续作答            有时  ...       5.5    5.666667        5.333333
4  实验情境4  我同意并愿意继续作答            偶尔  ...       5.0    4.000000        4.333333

[5 rows x 21 columns]

## 6. Validate

In [5]:
print("Final shape:", df.shape)
print("\nMissing values:")
display(df.isnull().sum().to_frame("missing_count"))

print("\nDuplicate rows:", df.duplicated().sum())

print("\nDtypes:")
display(df.dtypes)

df.to_csv(r"/mnt/data/questionnaire_cleaned.csv", index=False, encoding="utf-8-sig")
print("Saved cleaned file to: /mnt/data/questionnaire_cleaned.csv")

Final shape: (212, 21)

Missing values:

                missing_count
group                       0
consent                     0
shopping_freq               0
ai_purchase                 0
age_group                   0
wtp_open                    0
wtp_1                       0
wtp_2                       0
trust_1                     0
trust_2                     0
trust_3                     0
fam_1                       0
fam_2                       0
fam_3                       0
mc_ai                       0
mc_value                    0
design_source               0
added_value                 0
wtp_score                   0
trust_score                 0
ai_familiarity              0

Duplicate rows: 0

Dtypes:

group               object
consent             object
shopping_freq     category
ai_purchase       category
age_group         category
wtp_open             int64
wtp_1                int64
wtp_2                int64
trust_1              int64
trust_2              int64
trust_3              int64
fam_1                int64
fam_2                int64
fam_3                int64
mc_ai                int64
mc_value             int64
design_source        int64
added_value          int64
wtp_score          float64
trust_score        float64
ai_familiarity     float64
dtype: object

Saved cleaned file to: /mnt/data/questionnaire_cleaned.csv

## Cleaning summary
- Removed 1 non-response header row
- Dropped 3 fully empty `Unnamed:*` columns
- Converted rating variables and open-ended WTP to numeric
- Created:
  - `design_source` (1 = AI, 0 = professional design team)
  - `added_value` (1 = high, 0 = low)
  - `wtp_score`
  - `trust_score`
  - `ai_familiarity`
- Exported the cleaned dataset for downstream analysis